#pragma once

#define FALSE 0
#define TRUE 1

#define WINDOW_WIDTH 800
#define WINDOW_HEIGHT 600

#define FPS 60
#define FRAME_TARGET_TIME_MS (1000 / FPS)

#define BALL_SIZE 15
#define BALL_X_DEFAULT 20
#define BALL_Y_DEFAULT 20
#define BALL_DX_DEFAULT 2
#define BALL_DY_DEFAULT 2

#define PADDLE_WIDTH 20
#define PADDLE_HEIGHT (WINDOW_HEIGHT / 5)
#define PADDLES_X_OFFSET 30
#define PADDLE_MOVE_DY 15