#pragma once

#define FALSE 0
#define TRUE 1

#define WINDOW_WIDTH 800
#define WINDOW_HEIGHT 600

#define FPS 60
#define FRAME_TARGET_TIME_MS (1000 / FPS)

#define GAME_CONTROLLERS_MAX 2

#define GAME_SCREEN_TITLE_INDEX 0
#define GAME_SCREEN_GAME_INDEX 1
#define GAME_SCREEN_GAME_OVER_INDEX 2
#define GAME_SCREEN_TITLE_RUNS_GAME 0
#define GAME_SCREEN_GAME_RUNS_GAME 1
#define GAME_SCREEN_GAME_OVER_RUNS_GAME 0
#define GAME_SCREEN_GAME_OVER_MSG_HEIGHT 68
#define GAME_SCREEN_GAME_OVER_MSG_OFFSET GAME_SCREEN_GAME_OVER_MSG_HEIGHT

#define NET_DASH_WIDTH 3
#define NET_NUM_DASHES 21

#define BALL_SIZE 15
#define BALL_X_DEFAULT 20
#define BALL_Y_DEFAULT 20
#define BALL_DX_DEFAULT 2
#define BALL_DY_DEFAULT 2

#define PADDLE_WIDTH 20
#define PADDLE_HEIGHT (WINDOW_HEIGHT / 5)
#define PADDLES_X_OFFSET 30
#define PADDLE_MOVE_DY 10
#define PADDLES_NUM_MAX 2

#define SCORE_MIN 0
#define SCORE_MAX 1
#define SCORE_POINTS_INCREMENT 1
#define SCORE_NUM_SPRITE_WIDTH 64
#define SCORE_NUM_SPRITE_HEIGHT 64
#define SCORE_NUM_SPRITE_PADDING 24